"""Vendored clinical knowledge base — the deterministic tool backends for the
safety-catch engine. Copied verbatim (via AST extraction) from
data/generate_dataset.py so the detector and the eval share ONE ground-truth KB.

- DRUGS: per-drug class, RxNorm, renal caveat, teratogen flag, patient-language
  ADR symptoms, dangerous interaction pairs, and the allergy cross-reactivity class.
- ALLERGY_CROSS: charted allergy label -> set of drug classes that cross-react.
- LOINC_CODES: lab keys -> (LOINC code, display, unit) for the Chart Compiler.

Plus resolve_drug(): map a messy FHIR/free-text medication string to a KB key.
"""
from __future__ import annotations

DRUGS = {'atorvastatin': {'rxnorm': '617312',
                  'cls': 'statin',
                  'dose': '40 mg nightly',
                  'renal': None,
                  'teratogen': True,
                  'adr': ['muscle aches', 'muscle pain and weakness', 'aching in my legs'],
                  'interacts': {'clarithromycin': 'rhabdomyolysis / myopathy', 'gemfibrozil': 'myopathy'},
                  'allergy_class': 'statin'},
 'simvastatin': {'rxnorm': '312961',
                 'cls': 'statin',
                 'dose': '20 mg nightly',
                 'renal': None,
                 'teratogen': True,
                 'adr': ['muscle aches', 'leg cramps'],
                 'interacts': {'clarithromycin': 'rhabdomyolysis'},
                 'allergy_class': 'statin'},
 'metformin': {'rxnorm': '860975',
               'cls': 'biguanide',
               'dose': '1000 mg twice daily',
               'teratogen': False,
               'renal': {'threshold': 30,
                         'caution_below': 45,
                         'rule': 'contraindicated when eGFR < 30; do not start 30-45'},
               'adr': ['nausea and diarrhea', 'upset stomach'],
               'interacts': {},
               'allergy_class': None},
 'lisinopril': {'rxnorm': '197884',
                'cls': 'ACE inhibitor',
                'dose': '20 mg daily',
                'teratogen': True,
                'renal': {'hyperkalemia': True},
                'adr': ['dry hacking cough', 'tickle in my throat and a dry cough'],
                'interacts': {'potassium chloride': 'hyperkalemia',
                              'spironolactone': 'hyperkalemia',
                              'losartan': 'dual RAAS blockade',
                              'valsartan': 'dual RAAS blockade'},
                'allergy_class': 'ace_inhibitor'},
 'enalapril': {'rxnorm': '310809',
               'cls': 'ACE inhibitor',
               'dose': '10 mg twice daily',
               'teratogen': True,
               'renal': {'hyperkalemia': True},
               'adr': ['dry cough'],
               'interacts': {},
               'allergy_class': 'ace_inhibitor'},
 'losartan': {'rxnorm': '979485',
              'cls': 'ARB',
              'dose': '50 mg daily',
              'teratogen': True,
              'renal': {'hyperkalemia': True},
              'adr': ['dizziness'],
              'interacts': {'lisinopril': 'dual RAAS blockade'},
              'allergy_class': None},
 'amlodipine': {'rxnorm': '197361',
                'cls': 'calcium channel blocker',
                'dose': '10 mg daily',
                'renal': None,
                'teratogen': False,
                'adr': ['ankle swelling', 'swollen feet'],
                'interacts': {},
                'allergy_class': None},
 'hydrochlorothiazide': {'rxnorm': '310798',
                         'cls': 'thiazide diuretic',
                         'dose': '25 mg daily',
                         'renal': None,
                         'teratogen': False,
                         'adr': ['dizziness'],
                         'interacts': {},
                         'allergy_class': 'sulfa'},
 'metoprolol': {'rxnorm': '866514',
                'cls': 'beta blocker',
                'dose': '50 mg twice daily',
                'renal': None,
                'teratogen': False,
                'adr': ['fatigue', 'feeling really tired and slow'],
                'interacts': {},
                'allergy_class': None},
 'warfarin': {'rxnorm': '855332',
              'cls': 'anticoagulant',
              'dose': '5 mg daily',
              'renal': None,
              'teratogen': True,
              'adr': ['bruising easily', 'blood in my urine', 'bleeding gums'],
              'interacts': {'ibuprofen': 'major bleeding',
                            'naproxen': 'major bleeding',
                            'aspirin': 'major bleeding',
                            'amoxicillin': 'raised INR / bleeding',
                            'sulfamethoxazole-trimethoprim': 'raised INR / bleeding',
                            'fluconazole': 'raised INR'},
              'allergy_class': None},
 'apixaban': {'rxnorm': '1364430',
              'cls': 'anticoagulant (DOAC)',
              'dose': '5 mg twice daily',
              'teratogen': True,
              'renal': {'threshold': 25, 'rule': 'reduce / avoid at very low eGFR'},
              'adr': ['bruising', 'bleeding'],
              'interacts': {'ibuprofen': 'bleeding', 'naproxen': 'bleeding'},
              'allergy_class': None},
 'aspirin': {'rxnorm': '243670',
             'cls': 'antiplatelet/NSAID',
             'dose': '81 mg daily',
             'renal': None,
             'teratogen': False,
             'adr': ['stomach upset'],
             'interacts': {'warfarin': 'major bleeding'},
             'allergy_class': 'nsaid'},
 'ibuprofen': {'rxnorm': '5640',
               'cls': 'NSAID',
               'dose': '600 mg three times daily',
               'teratogen': True,
               'renal': {'threshold': 30, 'rule': 'avoid in advanced CKD'},
               'adr': ['stomach pain'],
               'interacts': {'warfarin': 'major bleeding',
                             'lisinopril': 'kidney injury / reduced BP control'},
               'allergy_class': 'nsaid'},
 'naproxen': {'rxnorm': '849574',
              'cls': 'NSAID',
              'dose': '500 mg twice daily',
              'teratogen': True,
              'renal': {'threshold': 30, 'rule': 'avoid in advanced CKD'},
              'adr': ['stomach pain'],
              'interacts': {'warfarin': 'major bleeding'},
              'allergy_class': 'nsaid'},
 'sertraline': {'rxnorm': '312940',
                'cls': 'SSRI',
                'dose': '100 mg daily',
                'renal': None,
                'teratogen': False,
                'adr': ['trouble sleeping', 'low sex drive', 'nausea'],
                'interacts': {'tramadol': 'serotonin syndrome',
                              'sumatriptan': 'serotonin syndrome',
                              'linezolid': 'serotonin syndrome'},
                'allergy_class': None},
 'tramadol': {'rxnorm': '836397',
              'cls': 'opioid analgesic',
              'dose': '50 mg every 6 hours',
              'renal': None,
              'teratogen': False,
              'adr': ['constipation', 'dizziness'],
              'interacts': {'sertraline': 'serotonin syndrome'},
              'allergy_class': 'opioid'},
 'sumatriptan': {'rxnorm': '313782',
                 'cls': 'triptan',
                 'dose': '50 mg as needed',
                 'renal': None,
                 'teratogen': False,
                 'adr': ['chest tightness'],
                 'interacts': {'sertraline': 'serotonin syndrome'},
                 'allergy_class': None},
 'amoxicillin': {'rxnorm': '723',
                 'cls': 'aminopenicillin',
                 'dose': '500 mg three times daily',
                 'renal': None,
                 'teratogen': False,
                 'adr': ['rash', 'diarrhea'],
                 'interacts': {'warfarin': 'raised INR'},
                 'allergy_class': 'penicillin'},
 'cephalexin': {'rxnorm': '309097',
                'cls': 'cephalosporin',
                'dose': '500 mg four times daily',
                'renal': None,
                'teratogen': False,
                'adr': ['diarrhea'],
                'interacts': {},
                'allergy_class': 'cephalosporin'},
 'sulfamethoxazole-trimethoprim': {'rxnorm': 'linkid_smx',
                                   'cls': 'sulfonamide antibiotic',
                                   'dose': '800/160 mg twice daily',
                                   'teratogen': True,
                                   'renal': {'hyperkalemia': True},
                                   'adr': ['rash'],
                                   'interacts': {'warfarin': 'raised INR / bleeding',
                                                 'lisinopril': 'hyperkalemia'},
                                   'allergy_class': 'sulfa'},
 'nitrofurantoin': {'rxnorm': '311989',
                    'cls': 'urinary antibiotic',
                    'dose': '100 mg twice daily',
                    'teratogen': False,
                    'renal': {'threshold': 30, 'rule': 'ineffective/toxic when eGFR < 30'},
                    'adr': ['nausea'],
                    'interacts': {},
                    'allergy_class': None},
 'nitroglycerin': {'rxnorm': '564666',
                   'cls': 'nitrate',
                   'dose': '0.4 mg sublingual as needed',
                   'renal': None,
                   'teratogen': False,
                   'adr': ['headache'],
                   'interacts': {'sildenafil': 'life-threatening hypotension'},
                   'allergy_class': None},
 'isosorbide mononitrate': {'rxnorm': '884173',
                            'cls': 'nitrate',
                            'dose': '30 mg daily',
                            'renal': None,
                            'teratogen': False,
                            'adr': ['headache'],
                            'interacts': {'sildenafil': 'life-threatening hypotension'},
                            'allergy_class': None},
 'sildenafil': {'rxnorm': '312349',
                'cls': 'PDE5 inhibitor',
                'dose': '50 mg as needed',
                'renal': None,
                'teratogen': False,
                'adr': ['flushing'],
                'interacts': {'nitroglycerin': 'life-threatening hypotension',
                              'isosorbide mononitrate': 'life-threatening hypotension'},
                'allergy_class': None},
 'levothyroxine': {'rxnorm': '966224',
                   'cls': 'thyroid hormone',
                   'dose': '100 mcg daily',
                   'renal': None,
                   'teratogen': False,
                   'adr': ['palpitations', 'heart racing and trouble sleeping'],
                   'interacts': {},
                   'allergy_class': None},
 'prednisone': {'rxnorm': '312615',
                'cls': 'corticosteroid',
                'dose': '20 mg daily',
                'renal': None,
                'teratogen': False,
                'adr': ['high blood sugars', 'trouble sleeping and mood swings'],
                'interacts': {},
                'allergy_class': None},
 'spironolactone': {'rxnorm': '313096',
                    'cls': 'potassium-sparing diuretic',
                    'dose': '25 mg daily',
                    'teratogen': False,
                    'renal': {'hyperkalemia': True},
                    'adr': ['breast tenderness'],
                    'interacts': {'lisinopril': 'hyperkalemia', 'potassium chloride': 'hyperkalemia'},
                    'allergy_class': None},
 'insulin glargine': {'rxnorm': '274783',
                      'cls': 'basal insulin',
                      'dose': '20 units nightly',
                      'renal': None,
                      'teratogen': False,
                      'adr': ['low blood sugar shakes', 'hypoglycemia'],
                      'interacts': {},
                      'allergy_class': None},
 'gabapentin': {'rxnorm': '310430',
                'cls': 'anticonvulsant',
                'dose': '300 mg three times daily',
                'teratogen': False,
                'renal': {'threshold': 30, 'rule': 'reduce dose in low eGFR'},
                'adr': ['drowsiness'],
                'interacts': {},
                'allergy_class': None},
 'albuterol': {'rxnorm': '801095',
               'cls': 'SABA inhaler',
               'dose': '2 puffs as needed',
               'renal': None,
               'teratogen': False,
               'adr': ['jittery, shaky hands'],
               'interacts': {},
               'allergy_class': None},
 'fluticasone-salmeterol': {'rxnorm': '896188',
                            'cls': 'ICS/LABA inhaler',
                            'dose': '1 puff twice daily',
                            'renal': None,
                            'teratogen': False,
                            'adr': ['hoarse voice'],
                            'interacts': {},
                            'allergy_class': None},
 'omeprazole': {'rxnorm': '402014',
                'cls': 'proton pump inhibitor',
                'dose': '20 mg daily',
                'renal': None,
                'teratogen': False,
                'adr': [],
                'interacts': {},
                'allergy_class': None},
 'furosemide': {'rxnorm': '310429',
                'cls': 'loop diuretic',
                'dose': '40 mg daily',
                'renal': None,
                'teratogen': False,
                'adr': ['dizziness when I stand'],
                'interacts': {},
                'allergy_class': 'sulfa'},
 'potassium chloride': {'rxnorm': '312961k',
                        'cls': 'potassium supplement',
                        'dose': '20 mEq daily',
                        'teratogen': False,
                        'renal': {'hyperkalemia': True},
                        'adr': [],
                        'interacts': {'lisinopril': 'hyperkalemia', 'spironolactone': 'hyperkalemia'},
                        'allergy_class': None}}

ALLERGY_CROSS = {'Penicillin': {'classes': {'penicillin'}, 'example_drug': 'amoxicillin', 'snomed': '373270004'},
 'Sulfa drugs': {'classes': {'sulfa'}, 'example_drug': 'sulfamethoxazole-trimethoprim', 'snomed': '3006004'},
 'NSAIDs': {'classes': {'nsaid'}, 'example_drug': 'ibuprofen', 'snomed': '293586001'},
 'ACE inhibitors (angioedema)': {'classes': {'ace_inhibitor'},
                                 'example_drug': 'lisinopril',
                                 'snomed': '293963004'},
 'Statins (myalgia)': {'classes': {'statin'}, 'example_drug': 'atorvastatin', 'snomed': '293992002'},
 'Codeine/opioids': {'classes': {'opioid'}, 'example_drug': 'tramadol', 'snomed': '294276004'}}

LOINC_CODES = {'egfr': ('33914-3', 'Glomerular filtration rate/1.73 sq M.predicted', 'mL/min/{1.73_m2}'),
 'scr': ('2160-0', 'Creatinine [Mass/volume] in Serum or Plasma', 'mg/dL'),
 'k': ('2823-3', 'Potassium [Moles/volume] in Serum or Plasma', 'mmol/L'),
 'a1c': ('4548-4', 'Hemoglobin A1c/Hemoglobin.total in Blood', '%'),
 'ldl': ('18262-3', 'LDL Cholesterol (direct)', 'mg/dL'),
 'inr': ('6301-6', 'INR in Platelet poor plasma by Coagulation assay', '{INR}'),
 'tsh': ('3016-3', 'Thyrotropin [Units/volume] in Serum or Plasma', 'm[IU]/L'),
 'sbp': ('8480-6', 'Systolic blood pressure', 'mm[Hg]'),
 'dbp': ('8462-4', 'Diastolic blood pressure', 'mm[Hg]'),
 'hr': ('8867-4', 'Heart rate', '/min'),
 'wt': ('29463-7', 'Body Weight', 'kg'),
 'bmi': ('39156-5', 'Body mass index (BMI) [Ratio]', 'kg/m2')}


# ---------------------------------------------------------------------------
# SUPPLEMENT — real pharmacology for drugs that appear in the FHIR bundles but
# were not in the synthetic generator's DRUGS table. This is general drug
# knowledge (class, renal handling, interactions, allergy class), NOT answer-key
# data — the detector still derives every flag itself. Same schema as DRUGS.
# ---------------------------------------------------------------------------
_SUPPLEMENT = {
    "ampicillin-sulbactam": {"rxnorm": "1659131", "cls": "aminopenicillin", "dose": "3 g IV q6h",
                             "renal": {"threshold": 30, "rule": "extend interval in low eGFR"},
                             "teratogen": False, "adr": ["rash", "diarrhea"], "interacts": {},
                             "allergy_class": "penicillin"},
    "enoxaparin": {"rxnorm": "854228", "cls": "anticoagulant (LMWH)", "dose": "40 mg SC daily",
                   "renal": {"threshold": 30, "rule": "reduce dose / accumulates when eGFR < 30"},
                   "teratogen": False, "adr": ["bruising", "bleeding"],
                   "interacts": {"apixaban": "additive bleeding / dual anticoagulation",
                                 "warfarin": "additive bleeding", "aspirin": "bleeding",
                                 "ibuprofen": "bleeding"}, "allergy_class": None},
    "oxycodone": {"rxnorm": "1049502", "cls": "opioid analgesic", "dose": "5 mg q6h PRN",
                  "renal": None, "teratogen": False, "adr": ["constipation", "drowsiness"],
                  "interacts": {"tramadol": "additive CNS/respiratory depression"},
                  "allergy_class": "opioid"},
    "acetaminophen": {"rxnorm": "161", "cls": "analgesic/antipyretic", "dose": "650 mg q6h PRN",
                      "renal": None, "teratogen": False, "adr": [], "interacts": {}, "allergy_class": None},
    "pantoprazole": {"rxnorm": "40790", "cls": "proton pump inhibitor", "dose": "40 mg daily",
                     "renal": None, "teratogen": False, "adr": [], "interacts": {}, "allergy_class": None},
    "ondansetron": {"rxnorm": "198012", "cls": "antiemetic (5-HT3)", "dose": "4 mg q8h PRN",
                    "renal": None, "teratogen": False, "adr": ["headache"], "interacts": {}, "allergy_class": None},
    "docusate": {"rxnorm": "82003", "cls": "stool softener", "dose": "100 mg BID",
                 "renal": None, "teratogen": False, "adr": [], "interacts": {}, "allergy_class": None},
}
# Tramadol IS renally cleared (base KB left it None); encode the real caveat so the
# renal check reasons about it like any other renally-dosed drug.
if DRUGS.get("tramadol") and DRUGS["tramadol"].get("renal") is None:
    DRUGS["tramadol"]["renal"] = {"threshold": 30, "rule": "accumulates + lowers seizure threshold when eGFR < 30"}

DRUGS.update({k: v for k, v in _SUPPLEMENT.items() if k not in DRUGS})


# Brand / verbose-name aliases the FHIR bundles use that don't substring-match a KB key.
_ALIASES = {
    "insulin": "insulin glargine",          # any insulin -> the insulin KB entry
    "humulin": "insulin glargine",          # brand human insulin -> map to the insulin KB entry
    "insulin isophane": "insulin glargine",
    "insulin, regular": "insulin glargine",
    "insulin regular": "insulin glargine",
    "novolog": "insulin glargine",
    "lantus": "insulin glargine",
    "glucophage": "metformin",
    "coumadin": "warfarin",
    "eliquis": "apixaban",
    "norvasc": "amlodipine",
    "lasix": "furosemide",
    "bactrim": "sulfamethoxazole-trimethoprim",
    "septra": "sulfamethoxazole-trimethoprim",
    "tylenol": "acetaminophen",
    "motrin": "ibuprofen",
    "advil": "ibuprofen",
    "aleve": "naproxen",
}

# Longest keys first so "insulin glargine" wins over a bare "insulin" substring, etc.
_DRUG_KEYS = sorted(DRUGS.keys(), key=len, reverse=True)
_ALIAS_KEYS = sorted(_ALIASES.keys(), key=len, reverse=True)


def resolve_drug(name: str | None) -> str | None:
    """Map a messy medication string (FHIR display, home-med label, transcript
    mention) to a canonical DRUGS key, or None if we don't know the drug.

    Matching is case-insensitive substring, longest-name-first, so
    '24 HR Metformin hydrochloride 500 MG ...' -> 'metformin' and
    'insulin isophane, human 70 UNT/ML [Humulin]' -> 'insulin glargine'.
    """
    if not name:
        return None
    n = name.lower()
    for key in _DRUG_KEYS:
        if key in n:
            return key
    for alias in _ALIAS_KEYS:
        if alias in n:
            return _ALIASES[alias]
    return None


def drug_class(name: str | None) -> str | None:
    key = resolve_drug(name)
    return DRUGS[key]["cls"] if key else None
