#!/usr/bin/env python3
"""
Synthea -> Discrepancy-Detector dataset.

Takes REAL Synthea FHIR-R4 patient bundles (generated by synthea/), and for each
one: selects a real ambulatory index encounter, reconciles the patient's real
active meds / allergies / problems / labs, then plants ONE labeled clinical
discrepancy (or leaves a clean control) using the injector library from
generate_dataset.py.

Grounding is REAL wherever the real chart supports it — a real eGFR of 24, a real
aspirin allergy, a real active statin — and only synthesized when the chart lacks
the needed substrate. Every record records per-item provenance (real vs injected).

Output = Abridge's exact 8-field schema + a separate labels sidecar. Reproducible.
"""
import json, glob, re, os, random, hashlib, datetime as dt
import generate_dataset as G

def sh(s):  # stable, process-independent hash for reproducible per-chart RNG
    return int.from_bytes(hashlib.md5(s.encode()).digest()[:4], "big")

OUT_DIR   = os.path.dirname(os.path.abspath(__file__))
POOL_MAIN = os.path.join(OUT_DIR, "synthea", "output_main", "fhir")
POOL_PREG = os.path.join(OUT_DIR, "synthea", "output_preg", "fhir")
SEED = 20260718
N_RECORDS = 100

# ---------------------------------------------------------------------------
# Vocabulary mapping: real Synthea strings -> our KB keys (for injector logic)
# ---------------------------------------------------------------------------
MED_TOKENS = {
  "metformin":"metformin","lisinopril":"lisinopril","enalapril":"enalapril","losartan":"losartan",
  "atorvastatin":"atorvastatin","simvastatin":"simvastatin","amlodipine":"amlodipine",
  "hydrochlorothiazide":"hydrochlorothiazide","metoprolol":"metoprolol","warfarin":"warfarin",
  "apixaban":"apixaban","aspirin":"aspirin","ibuprofen":"ibuprofen","naproxen":"naproxen",
  "sertraline":"sertraline","tramadol":"tramadol","sumatriptan":"sumatriptan","amoxicillin":"amoxicillin",
  "cephalexin":"cephalexin","nitrofurantoin":"nitrofurantoin","levothyroxine":"levothyroxine",
  "prednisone":"prednisone","spironolactone":"spironolactone","glargine":"insulin glargine",
  "gabapentin":"gabapentin","albuterol":"albuterol","fluticasone":"fluticasone-salmeterol",
  "omeprazole":"omeprazole","furosemide":"furosemide",
}
def map_med(text):
    t=(text or "").lower()
    for tok,key in MED_TOKENS.items():
        if tok in t: return key
    return None

COND_RULES = [
  ("diabetes mellitus type 2","Type 2 diabetes mellitus"),("diabetes","Type 2 diabetes mellitus"),
  ("hypertension","Essential hypertension"),
  ("chronic kidney disease stage 4","Chronic kidney disease stage 4"),
  ("chronic kidney disease stage 5","Chronic kidney disease stage 4"),
  ("chronic kidney disease stage 3","Chronic kidney disease stage 3"),
  ("chronic kidney disease","Chronic kidney disease stage 3"),
  ("hyperlipidemia","Hyperlipidemia"),("hypercholesterolemia","Hyperlipidemia"),
  ("atrial fibrillation","Atrial fibrillation"),("coronary","Coronary artery disease"),
  ("myocardial infarction","Coronary artery disease"),
  ("major depress","Major depressive disorder"),("depression","Major depressive disorder"),
  ("anxiety","Generalized anxiety disorder"),("migraine","Migraine without aura"),
  ("hypothyroid","Hypothyroidism"),("asthma","Asthma"),("pulmonary disease","COPD"),
  ("pregnan","Pregnancy"),("reflux","Gastroesophageal reflux disease"),
  ("osteoarthritis","Osteoarthritis"),("urinary tract","Recurrent urinary tract infection"),
  ("low back pain","Chronic low back pain"),
]
def map_condition(display):
    d=(display or "").lower()
    for needle,label in COND_RULES:
        if needle in d: return label
    return None

ALLERGY_RULES = [
  ("penicillin","Penicillin"),("amoxicillin","Penicillin"),("cefdinir","Penicillin"),
  ("cephalosporin","Penicillin"),("sulfa","Sulfa drugs"),("sulfonamide","Sulfa drugs"),
  ("aspirin","NSAIDs"),("ibuprofen","NSAIDs"),("naproxen","NSAIDs"),("nsaid","NSAIDs"),
  ("lisinopril","ACE inhibitors (angioedema)"),("enalapril","ACE inhibitors (angioedema)"),
  ("codeine","Codeine/opioids"),("morphine","Codeine/opioids"),
]
def map_allergy(display):
    d=(display or "").lower()
    for needle,label in ALLERGY_RULES:
        if needle in d: return label
    return None

def clean_name(s):
    return re.sub(r"\d+","", s or "").strip() or "Alex"

# ---------------------------------------------------------------------------
# Real-chart extraction
# ---------------------------------------------------------------------------
def load_bundle(path):
    b=json.load(open(path))
    res=[e["resource"] for e in b.get("entry",[])]
    return res

def latest_obs(res, code, as_of=None):
    hits=[o for o in res if o["resourceType"]=="Observation"
          and any(c.get("code")==code for c in o.get("code",{}).get("coding",[]))
          and o.get("valueQuantity")]
    if as_of: hits=[o for o in hits if (o.get("effectiveDateTime","") or "")[:10] <= as_of]
    if not hits: return None
    hits.sort(key=lambda o:o.get("effectiveDateTime",""))
    return hits[-1]

def amb_encounters(res):
    encs=[r for r in res if r["resourceType"]=="Encounter" and r.get("class",{}).get("code")=="AMB"
          and r.get("period",{}).get("start")]
    encs.sort(key=lambda e:e["period"]["start"])
    return encs

def pick_index_encounter(res):
    encs=amb_encounters(res)
    if not encs: encs=[r for r in res if r["resourceType"]=="Encounter"]
    if not encs: return None
    def score(e):
        t=(e.get("type",[{}])[0].get("text","") or "").lower()
        pref = 2 if "general examination" in t else (1 if "check up" in t else 0)
        return (pref, e.get("period",{}).get("start",""))
    return sorted(encs,key=score)[-1]

class SChart:
    """Bridges a real Synthea bundle into the shape the injectors expect.
       If target_enc is given, the chart reflects the patient state AS-OF that
       real encounter's date (for longitudinal series)."""
    def __init__(self, rng, path, res, target_enc=None):
        self.rng=rng; self.path=path; self.res=res
        self.patient=next(r for r in res if r["resourceType"]=="Patient")
        self.pid=self.patient["id"]
        self.gender=self.patient.get("gender","female")
        nm=self.patient["name"][0]
        self.given=clean_name((nm.get("given") or ["Alex"])[0])
        self.family=clean_name(nm.get("family","Doe"))
        self.birth=dt.date.fromisoformat(self.patient["birthDate"])
        self.name_display=f"{('Mr.' if self.gender=='male' else 'Ms.')} {self.given} {self.family}"
        self.all_amb=amb_encounters(res)
        self.index=target_enc or pick_index_encounter(res)
        self.enc_id=self.index["id"] if self.index else self.pid
        self.when_dt=self.index.get("period",{}).get("start","")[:10] if self.index else "2025-01-01"
        yr=int(self.when_dt[:4]); self.age=yr-self.birth.year
        self.archetype="synthea"
        aod=self.when_dt
        # real active meds AS-OF this visit -> our keys (dedup, keep resource for evidence passthrough)
        self.real_med_res=[m for m in res if m["resourceType"]=="MedicationRequest" and m.get("status")=="active"
                           and (m.get("authoredOn","") or "")[:10] <= aod]
        self.home_meds=[]
        for m in self.real_med_res:
            k=map_med(m.get("medicationCodeableConcept",{}).get("text"))
            if k and k not in self.home_meds: self.home_meds.append(k)
        # real active conditions AS-OF -> our labels + keep display list
        self.real_cond_res=[c for c in res if c["resourceType"]=="Condition"
                            and c.get("clinicalStatus",{}).get("coding",[{}])[0].get("code")=="active"
                            and ((c.get("onsetDateTime") or c.get("recordedDate") or "")[:10] <= aod)]
        self.conditions=[]; self.cond_displays=[]
        for c in self.real_cond_res:
            disp=c["code"]["coding"][0].get("display","")
            self.cond_displays.append(disp)
            lab=map_condition(disp)
            if lab and lab not in self.conditions: self.conditions.append(lab)
        # real allergies (chronic; include those recorded before the visit)
        self.real_allergy_res=[a for a in res if a["resourceType"]=="AllergyIntolerance"
                               and ((a.get("recordedDate","") or "")[:10] <= aod or not a.get("recordedDate"))]
        self.allergy=None; self.real_allergy_label=None
        for a in self.real_allergy_res:
            lab=map_allergy(a.get("code",{}).get("text") or a["code"]["coding"][0].get("display",""))
            if lab: self.allergy=lab; self.real_allergy_label=lab; break
        # labs AS-OF
        e=latest_obs(res,"33914-3",aod); self.egfr = round(e["valueQuantity"]["value"]) if e else None
        self.egfr_res=e
        self.a1c_res=latest_obs(res,"4548-4",aod); self.k_res=latest_obs(res,"6298-4",aod)

# ---------------------------------------------------------------------------
# Emit one record from a real chart + an injector result
# ---------------------------------------------------------------------------
def bp_from(res, enc_id):
    """pull systolic/diastolic/hr/weight from the index encounter (or latest)."""
    def comp(o,code):
        for c in o.get("component",[]):
            if any(cc.get("code")==code for cc in c.get("code",{}).get("coding",[])):
                return c.get("valueQuantity",{}).get("value")
    obs=[o for o in res if o["resourceType"]=="Observation"]
    def latest(pred):
        hs=[o for o in obs if pred(o)]; hs.sort(key=lambda o:o.get("effectiveDateTime","")); return hs[-1] if hs else None
    bp=latest(lambda o:any(c.get("code")=="85354-9" for c in o.get("code",{}).get("coding",[])))
    hr=latest(lambda o:any(c.get("code")=="8867-4" for c in o.get("code",{}).get("coding",[])))
    wt=latest(lambda o:any(c.get("code")=="29463-7" for c in o.get("code",{}).get("coding",[])))
    sbp=comp(bp,"8480-6") if bp else None; dbp=comp(bp,"8462-4") if bp else None
    return (round(sbp) if sbp else 128, round(dbp) if dbp else 78,
            round(hr["valueQuantity"]["value"]) if hr else 74,
            round(wt["valueQuantity"]["value"]) if wt else 80)

def emit(sc, injected):
    rng=sc.rng; res=sc.res; pid=sc.pid; enc=sc.enc_id
    when=dt.date.fromisoformat(sc.when_dt)
    grounding={}

    related={"Condition":[],"Observation":[],"MedicationRequest":[],"AllergyIntolerance":[],"Procedure":[]}
    # --- real active problems (cap the social-finding noise but keep clinical ones) ---
    for c in sc.real_cond_res:
        related["Condition"].append(c)
    # --- real active meds (reconciled at visit); a silently-discontinued med is omitted ---
    drop_med=injected.get("_drop_active_med")
    for m in sc.real_med_res:
        if drop_med and map_med(m.get("medicationCodeableConcept",{}).get("text"))==drop_med: continue
        related["MedicationRequest"].append(m)
    # --- real allergies ---
    for a in sc.real_allergy_res:
        related["AllergyIntolerance"].append(a)
    # --- real vitals + labs carried into the visit ---
    sbp,dbp,hr,wt=bp_from(res,enc)
    for key,val in [("sbp",sbp),("dbp",dbp),("hr",hr),("wt",wt)]:
        related["Observation"].append(G.mk_obs(G.uid(rng),pid,enc,key,val,when,category="vital-signs"))
    if sc.egfr_res: related["Observation"].append(sc.egfr_res); grounding["egfr"]="real"
    if sc.a1c_res:  related["Observation"].append(sc.a1c_res)
    if sc.k_res:    related["Observation"].append(sc.k_res)

    # ---- apply injector chart mutations, preferring real substrate ----
    # allergy
    if injected["ensure_allergy"]:
        lab=injected["ensure_allergy"]
        real_present = any(map_allergy(a.get("code",{}).get("text") or a["code"]["coding"][0].get("display","") )==lab
                           for a in sc.real_allergy_res)
        if real_present: grounding["allergy"]="real"
        else:
            related["AllergyIntolerance"].append(G.mk_allergy(G.uid(rng),pid,lab,when-dt.timedelta(days=900)))
            grounding["allergy"]="injected"
    # egfr override (only if injector forces a value the real chart doesn't already satisfy)
    if injected["set_egfr"] is not None:
        if sc.egfr is not None and sc.egfr==injected["set_egfr"]:
            grounding["egfr"]="real"
        else:
            related["Observation"].append(G.mk_obs(G.uid(rng),pid,enc,"egfr",injected["set_egfr"],when))
            grounding["egfr"]= grounding.get("egfr","injected") if grounding.get("egfr")=="real" else "injected"
    # ensure a specific home med exists (DDI partner)
    for drug in injected["ensure_home_med"]:
        if drug not in sc.home_meds:
            related["MedicationRequest"].append(G.mk_med(G.uid(rng),pid,enc,drug,when-dt.timedelta(days=600),status="active"))
            grounding.setdefault("home_med","injected")
        else:
            grounding.setdefault("home_med","real")
    # newly prescribed this visit (the action being flagged)
    for drug in injected["prescribe"]:
        related["MedicationRequest"].append(G.mk_med(G.uid(rng),pid,enc,drug,when,status="active"))
    # extra labs the injector wants (e.g. dropped_result abnormal prior value)
    for key,val in injected["labs"].items():
        if key=="egfr" and grounding.get("egfr"): continue
        when_lab=when - dt.timedelta(days=injected.get("prior_lab_days",0))
        related["Observation"].append(G.mk_obs(G.uid(rng),pid,enc,key,val,when_lab))
    # carried-forward / injected temporal resources (prior referral, stopped med, prior abnormal obs)
    for rtype,resource in injected.get("extra_resources",[]):
        related.setdefault(rtype,[]).append(resource)

    # default grounding tags for real-substrate injectors
    if injected["type"] in ("drug_drug_interaction","duplicate_therapy","dropped_home_med") and "home_med" not in grounding:
        grounding["home_med"]="real"
    if injected["type"]=="renal_dose_conflict" and sc.egfr is not None and sc.egfr<30 and not injected["set_egfr"]:
        grounding["egfr"]="real"
    if injected["adverse_event_label"]:
        grounding["ade_med"]="real" if injected["adverse_event_label"].get("suspected_drug") in sc.home_meds else "injected"

    # ---- resolve label evidence against related resources (semantic, not substring) ----
    def _disp(r):
        return (r.get("code",{}).get("text") or r.get("medicationCodeableConcept",{}).get("text")
                or r.get("code",{}).get("coding",[{}])[0].get("display",""))
    def resolve(item):
        if not item: return
        ce=item.get("chart_evidence")
        if not ce: return
        target=ce.get("match_display",""); tl=target.lower(); wt=ce["resource_type"]
        cands=related.get(wt,[]); pick=None
        for r in cands:
            d=_disp(r)
            if wt=="AllergyIntolerance" and (map_allergy(d)==target or tl in d.lower()): pick=r;break
            if wt=="Condition" and (map_condition(d)==target or tl in d.lower()): pick=r;break
            if wt=="MedicationRequest" and (map_med(d)==target or tl in d.lower()): pick=r;break
            if wt=="Observation" and (tl in d.lower() or tl in json.dumps(r).lower()): pick=r;break
        if pick is None:                      # last-resort raw substring over any field
            for r in cands:
                if tl and tl in json.dumps(r).lower(): pick=r;break
        if pick is not None:
            ce["resource_id"]=pick["id"]; ce["display"]=_disp(pick)
        ce.pop("match_display",None)
    resolve(injected["discrepancy_label"]); resolve(injected["adverse_event_label"])

    # ================= TRANSCRIPT / NOTE / AVS =================
    transcript,note,avs = s_assemble(sc, injected, sbp,dbp,hr,wt)

    # ================= longitudinal summary (real counts) =================
    from collections import Counter
    rc=Counter(r["resourceType"] for r in res)
    med_labels=sorted({m.get("medicationCodeableConcept",{}).get("text","") for m in sc.real_med_res} |
                      {f"{d} {G.DRUGS[d]['dose']}" for d in injected["prescribe"]})
    allergy_labels=sorted({(a.get("code",{}).get("text") or a["code"]["coding"][0].get("display","")) for a in sc.real_allergy_res}
                          | ({injected["ensure_allergy"]} if injected["ensure_allergy"] and grounding.get("allergy")=="injected" else set()))

    visit_title=f"Follow-up visit — {', '.join([c for c in sc.conditions[:2]] or ['adult primary care'])}"
    record={
      "id":f"{pid}::{enc}",
      "metadata":{
        "source":"synthea-fhir-r4+discrepancy-injection","synthetic":True,
        "patient_id":pid,"encounter_id":enc,"encounter_reference":G.urn(enc),
        "date":G.iso(when),"status":"finished",
        "visit_type":(sc.index.get("type",[{}])[0].get("text") if sc.index else "General examination of patient (procedure)"),
        "document_status":"current",
        "related_resource_counts":{k:len(v) for k,v in related.items() if v},
        "visit_title":visit_title,
      },
      "patient_context":{
        "patient":sc.patient,
        "longitudinal_summary":{
          "resource_counts":dict(rc),
          "condition_labels":sc.cond_displays,
          "medication_labels":med_labels,
          "allergy_labels":allergy_labels,
        },
      },
      "encounter_fhir":{
        "encounter":sc.index or G.mk_encounter(enc,pid,when,"General examination of patient (procedure)",sc.name_display),
        "related_resources":{k:v for k,v in related.items() if v},
      },
      "transcript":transcript,"note":note,"after_visit_summary":avs,
      "after_visit_summary_provenance":{"method":"template_extractive_v1",
        "source":"clinical_note_assessment_and_plan","review_status":"not_clinically_reviewed"},
    }
    discs=[injected["discrepancy_label"]] if injected["discrepancy_label"] else []
    ades=[injected["adverse_event_label"]] if injected["adverse_event_label"] else []
    for d in discs: d["grounding"]=grounding
    label={"id":record["id"],"source":"synthea","archetype":"synthea:"+("+".join(sc.conditions[:3]) or "well"),
           "has_discrepancy":bool(discs),"discrepancies":discs,
           "has_adverse_event":bool(ades),"adverse_events":ades,
           "is_control":injected["type"] is None,"grounding":grounding}
    return record,label

def s_assemble(sc, injected, sbp,dbp,hr,wt):
    L=G.line; nm=sc.given
    spoken_conditions=[re.sub(r"\s*\((disorder|finding|situation|morphologic abnormality)\)","",d)
                       for d in sc.cond_displays
                       if not any(w in d.lower() for w in ["employ","education","stress","social","housing",
                       "medication review","risk activity","transport","violence","labor force","income","received"])][:4]
    T=[]
    T.append(L("DR", sc.rng.choice([f"Hi {nm}, good to see you again.",f"{nm}, come on in — how have you been?"])))
    T.append(L("PT", sc.rng.choice(["Doing okay, thanks.","Good to see you, doctor."])))
    T.append(L("DR","Anything new since your last visit?"))
    T += (injected["hpi_turns"] or [L("PT","Nothing major, staying about the same.")])
    T += (injected["review_turns"] or [
        L("DR","Let me confirm your medications."),
        L("PT","Same as before — "+(", ".join(sc.home_meds) if sc.home_meds else "nothing regular")+"."),
        L("DR","That matches my list.")])
    T.append(L("NURSE",f"BP {sbp} over {dbp}, heart rate {hr}, weight {wt} kilos."))
    labbits=[]
    if sc.egfr is not None: labbits.append(f"kidney function eGFR {sc.egfr}")
    if sc.a1c_res: labbits.append(f"A1c {sc.a1c_res['valueQuantity']['value']:.1f} percent")
    if labbits: T.append(L("DR","Your labs — "+", ".join(labbits)+"."))
    T.append(L("DR","Let's talk about the plan."))
    T += (injected["plan_turns"] or [L("DR","No changes today — keep on as you are."),L("PT","Sounds good.")])
    T.append(L("DR","Any questions before you head out?"))
    T.append(L("PT","No, thank you."))
    transcript="\n".join(T)

    sex="man" if sc.gender=="male" else "woman"
    subj=[f"{nm} {sc.family} is a {sc.age}-year-old {sex} here for follow-up."]
    if spoken_conditions: subj.append("Active problems include "+", ".join(c.lower() for c in spoken_conditions)+".")
    for t in injected["hpi_turns"]+injected["review_turns"]:
        spk,txt=t.split(": ",1)
        if spk=="PT" and any(w in txt for w in ["ran out","new","cough","muscle","swelling","never heard","bloodwork"]):
            subj.append("Patient reports: "+txt)
    objective=(f"Vitals: BP {sbp}/{dbp} mmHg, HR {hr}/min, weight {wt} kg. Exam: no acute distress. "
               f"Labs: "+(f"eGFR {sc.egfr} mL/min/1.73m2" if sc.egfr is not None else "reviewed")+".")
    plan_items=injected["note_plan_items"] or [("Chronic disease management","Stable; continue current regimen.")]
    ap=["**Assessment and Plan:**",""]
    for h,b in plan_items: ap += [f"### {h}",b,""]
    note=(f"**Subjective:** {' '.join(subj)}\n\n**Objective:** {objective}\n\n"+"\n".join(ap)).strip()
    nexts=injected["avs_next"] or ["Continue current care.","Return as scheduled."]
    avs=("Visit summary\n\nWhat we discussed\n"+"\n".join("• "+h for h,_ in plan_items)
         +"\n\nNext steps\n"+"\n".join("• "+n for n in nexts))
    return transcript,note,avs

# ---------------------------------------------------------------------------
# Selection + main
# ---------------------------------------------------------------------------
def real_pref(sc, disc_type):
    """True if this real chart already contains the substrate for disc_type."""
    if disc_type=="drug_allergy_conflict": return sc.real_allergy_label is not None
    if disc_type=="renal_dose_conflict":   return sc.egfr is not None and sc.egfr<30
    if disc_type=="drug_condition_conflict":return "Pregnancy" in sc.conditions
    if disc_type=="dropped_result":         return sc.egfr is not None or bool(sc.a1c_res) or "warfarin" in sc.home_meds
    if disc_type in ("drug_drug_interaction","duplicate_therapy","dropped_home_med","adverse_drug_event"):
        return len(sc.home_meds)>=1
    if disc_type=="history_mismatch":       return len(sc.conditions)>=1
    return True

# ---------------------------------------------------------------------------
# Temporal (cross-visit) discrepancy builders for the longitudinal slice
# ---------------------------------------------------------------------------
def mk_service_request(rng, pid, enc, specialty, when):
    return {"resourceType":"ServiceRequest","id":G.uid(rng),"status":"active","intent":"order",
            "code":{"text":f"Referral to {specialty}"},"subject":{"reference":G.urn(pid)},
            "encounter":{"reference":G.urn(enc)},"authoredOn":G.iso(when)}

def choose_window(encs, L):
    if len(encs)<L: return None
    tail=encs[-min(len(encs),8):]
    if len(tail)<L: tail=encs[-L:]
    idxs=sorted(set(round(k*(len(tail)-1)/(L-1)) for k in range(L)))
    seen=set(); win=[]
    for i in idxs:
        d=tail[i]["period"]["start"][:10]
        if d in seen: continue
        seen.add(d); win.append(tail[i])
    return win if len(win)>=2 else None

def _trend_label(analyte, series, injs, last, setup):
    vals=", ".join(f"{v:g}" for _,v in series)
    matchd="glomerular" if analyte=="eGFR" else "hemoglobin a1c"
    ev=G.line("DR", f"Your {analyte} has gone {vals} across these visits — we'll hold the current plan.")
    li=injs[last.enc_id]
    li["hpi_turns"]=[ev]
    li["note_plan_items"]=[(f"{analyte} trend","Values reviewed; regimen unchanged today.")]
    li["avs_next"]=["No changes to your medications today."]
    tl={"type":"worsening_trend","severity":"high" if analyte=="eGFR" else "moderate","analyte":analyte,
        "series":[{"date":d,"value":v} for d,v in series],
        "explanation":f"{analyte} is trending the wrong way across visits ({vals}) yet the plan is unchanged, with no escalation or workup.",
        "transcript_evidence":ev,"chart_evidence":{"resource_type":"Observation","match_display":matchd},
        "suggested_fix":f"Do not leave the worsening {analyte} unaddressed — escalate therapy/workup and document the trend."}
    return tl, {"trend":"real","analyte":analyte}

def _fallback_label(pick, charts, injs, last, setup, rng):
    if pick=="med_discontinued":
        important={"atorvastatin","simvastatin","lisinopril","enalapril","metoprolol","insulin glargine",
                   "levothyroxine","warfarin","metformin","amlodipine"}
        med=next((m for m in setup.home_meds if m in important), (setup.home_meds[0] if setup.home_meds else None))
        if med:
            li=injs[last.enc_id]
            stopped=G.mk_med(G.uid(rng),last.pid,last.enc_id,med,dt.date.fromisoformat(setup.when_dt),status="stopped")
            li["extra_resources"]=[("MedicationRequest",stopped)]; li["_drop_active_med"]=med
            ev=G.line("PT", f"I realized I'm not on the {med} anymore — I don't think anyone told me to stop it.")
            li["hpi_turns"]=[ev]; li["note_plan_items"]=[("Medication reconciliation","Reviewed current medications.")]
            tl={"type":"med_discontinued_without_reason","severity":"high" if med in ("warfarin","insulin glargine") else "moderate",
                "drug":med,"prior_visit":setup.when_dt,
                "explanation":f"{med} was active at the {setup.when_dt} visit but is absent from today's reconciled list with no documented reason for stopping.",
                "transcript_evidence":ev,"chart_evidence":{"resource_type":"MedicationRequest","match_display":med},
                "suggested_fix":f"Reconcile {med}: confirm whether the stop was intentional; restart or document the rationale."}
            return tl, {"home_med":"real"}
        pick="dropped_result"
    if pick=="dropped_referral":
        specialty=rng.choice(["nephrology","cardiology","endocrinology"])
        when_setup=dt.date.fromisoformat(setup.when_dt)
        si=injs[setup.enc_id]
        si["extra_resources"]=[("ServiceRequest",mk_service_request(rng,setup.pid,setup.enc_id,specialty,when_setup))]
        si["plan_turns"]=[G.line("DR",f"I'm putting in a referral to {specialty} for you today."),G.line("PT","Okay, thanks.")]
        si["note_plan_items"]=[("Referral",f"Referral to {specialty} placed.")]
        si["avs_next"]=[f"See {specialty} as referred."]
        li=injs[last.enc_id]
        li["extra_resources"]=[("ServiceRequest",mk_service_request(rng,last.pid,setup.enc_id,specialty,when_setup))]
        ev=G.line("PT", f"I still haven't managed to get in to see {specialty}, by the way.")
        li["hpi_turns"]=[ev, G.line("DR","Let's move on — how's everything else?")]
        li["note_plan_items"]=[("Interval history","No acute issues reported.")]
        tl={"type":"dropped_referral","severity":"moderate","specialty":specialty,"prior_visit":setup.when_dt,
            "explanation":f"A referral to {specialty} was placed at the {setup.when_dt} visit; the patient still hasn't been seen and today's plan does not follow up on it.",
            "transcript_evidence":ev,"chart_evidence":{"resource_type":"ServiceRequest","match_display":f"referral to {specialty}"},
            "suggested_fix":f"Close the loop on the {specialty} referral: verify scheduling, re-refer if needed, and document."}
        return tl, {"referral":"injected"}
    # dropped_result
    if "Type 2 diabetes mellitus" in setup.conditions: analyte,val,phrase,key,matchd=("A1c",9.8,"an A1c of 9.8%","a1c","hemoglobin a1c")
    else: analyte,val,phrase,key,matchd=("potassium",5.8,"a high potassium of 5.8","k","potassium")
    si=injs[setup.enc_id]
    si["labs"]={key:val}
    si["plan_turns"]=[G.line("DR",f"Your {analyte} came back high at {val} — let's recheck it next time."),G.line("PT","Sure.")]
    si["note_plan_items"]=[("Abnormal result",f"{analyte} {val}; recheck at next visit.")]
    li=injs[last.enc_id]
    days=max((dt.date.fromisoformat(last.when_dt)-dt.date.fromisoformat(setup.when_dt)).days,1)
    li["labs"]={key:val}; li["prior_lab_days"]=days
    ev=G.line("PT", f"Did that {analyte} from last time ever get rechecked? I never heard back.")
    li["hpi_turns"]=[ev, G.line("DR","We'll set that aside for today.")]
    li["note_plan_items"]=[("Follow-up","Continue current plan.")]
    tl={"type":"dropped_result","severity":"high" if key=="k" else "moderate","prior_visit":setup.when_dt,
        "explanation":f"An abnormal {phrase} at the {setup.when_dt} visit was flagged for recheck but is never followed up today.",
        "transcript_evidence":ev,"chart_evidence":{"resource_type":"Observation","match_display":matchd},
        "suggested_fix":f"Address the deferred {phrase}: repeat and act on it now; do not carry it forward unresolved."}
    return tl, {"prior_result":"injected"}

def _point_in_time(sc):
    """apply a point-in-time injector to a single visit (earlier visits in a series
       get their own catches). Prefer types the REAL chart supports; drug_allergy is
       last since it can always inject a synthetic allergy (keeps grounding real and
       the distribution balanced)."""
    med=["drug_drug_interaction","dropped_home_med","adverse_drug_event","duplicate_therapy","renal_dose_conflict"]
    sc.rng.shuffle(med)
    # medication-based real catches first; history/allergy only when no med catch applies
    for t in med + ["history_mismatch","drug_allergy_conflict"]:
        inj=G.INJECTORS[t](sc, sc.rng)
        if inj is not None: return inj
    return None

def longitudinal_patient(f, res, rng, variant):
    encs=amb_encounters(res)
    if len(encs)<4: return None
    L=rng.choice([2,3,3,4])
    window=choose_window(encs,L)
    if not window or len(window)<2: return None
    charts=[SChart(random.Random(sh(f+e["id"])), f, res, target_enc=e) for e in window]
    injs={}
    for c in charts:
        b=G._blank()
        b["note_plan_items"]=[("Chronic disease management","Stable; continue current regimen.")]
        b["plan_turns"]=[G.line("DR","Let's keep things as they are for now."),G.line("PT","Okay.")]
        b["avs_next"]=["Continue your current medications.","Return as scheduled."]
        injs[c.enc_id]=b
    setup=charts[0]; last=charts[-1]
    egfr_series=[(c.when_dt,c.egfr) for c in charts if c.egfr is not None]
    a1c_series=[(c.when_dt,c.a1c_res["valueQuantity"]["value"]) for c in charts if c.a1c_res]
    tl=grounding=None
    if len(egfr_series)>=3 and (egfr_series[0][1]-egfr_series[-1][1])>=8 and egfr_series[0][1]>egfr_series[-1][1]>0:
        tl,grounding=_trend_label("eGFR",egfr_series,injs,last,setup)
    elif len(a1c_series)>=3 and (a1c_series[-1][1]-a1c_series[0][1])>=1.0:
        tl,grounding=_trend_label("A1c",a1c_series,injs,last,setup)
    if tl is None:
        pick=["med_discontinued","dropped_referral","dropped_result","worsening_forced"][variant%4]
        if pick=="worsening_forced" and len(egfr_series)>=2:   # rotate a worsening case in even if mild
            tl,grounding=_trend_label("eGFR",egfr_series,injs,last,setup)
        else:
            if pick=="worsening_forced": pick="dropped_result"
            tl,grounding=_fallback_label(pick,charts,injs,last,setup,rng)
    injs[last.enc_id]["discrepancy_label"]=tl; injs[last.enc_id]["type"]=tl["type"]
    # earlier, non-reserved visits carry their own point-in-time catch
    reserved={last.enc_id}
    if tl["type"] in ("dropped_result","dropped_referral"): reserved.add(setup.enc_id)
    for c in charts:
        if c.enc_id in reserved: continue
        pit=_point_in_time(c)
        if pit is not None: injs[c.enc_id]=pit
    recs=[]; labs=[]
    for i,c in enumerate(charts):
        rec,lab=emit(c, injs[c.enc_id])
        lab["series"]={"visit_index":i,"n_visits":len(charts),"date":c.when_dt,
                       "prior_encounter_id": charts[i-1].enc_id if i>0 else None}
        if c.enc_id==last.enc_id:
            lab["temporal"]=True; lab["prior_encounter_id"]=setup.enc_id
            if lab["discrepancies"]: lab["discrepancies"][0]["grounding"]=grounding
        recs.append(rec); labs.append(lab)
    return recs,labs

def main():
    rng=random.Random(SEED)
    def load_pool(d):
        out=[]
        for f in sorted(glob.glob(os.path.join(d,"*.json"))):
            if any(x in f for x in ["hospitalInformation","practitionerInformation"]): continue
            res=load_bundle(f)
            if not any(r["resourceType"]=="Patient" for r in res): continue
            if not any(r["resourceType"]=="Encounter" for r in res): continue
            out.append((f,res))
        return out
    main_pool=load_pool(POOL_MAIN)
    preg_pool=load_pool(POOL_PREG)
    rng.shuffle(main_pool); rng.shuffle(preg_pool)
    used=set()

    # ---------- LONGITUDINAL SLICE: ~25 patients as 2-4 real-visit series ----------
    L_recs=[]; L_labs=[]; variant=0; n_series=0
    for f,res in main_pool:
        if len(L_recs)>=64 or n_series>=26: break
        if f in used or len(amb_encounters(res))<4: continue
        out=longitudinal_patient(f,res,rng,variant)
        if not out or len(out[0])<2: continue
        used.add(f); L_recs+=out[0]; L_labs+=out[1]; variant+=1; n_series+=1

    # ---------- SINGLE-VISIT POINT-IN-TIME FILL (to 100) ----------
    def take(disc_type):
        pool = preg_pool if disc_type=="drug_condition_conflict" else main_pool
        injector=G.INJECTORS["control" if disc_type=="control" else disc_type]
        for require_real in (True, False):
            for f,res in pool:
                if f in used: continue
                sc=SChart(random.Random(sh(f)), f, res)
                if disc_type=="drug_condition_conflict" and "Pregnancy" not in sc.conditions: continue
                if require_real and not real_pref(sc, disc_type): continue
                injected=injector(sc, sc.rng)
                if injected is None: continue
                rec,lab=emit(sc, injected)
                used.add(f); return rec,lab
        return None
    remaining=N_RECORDS-len(L_recs)
    weights={"control":20,"drug_allergy_conflict":13,"drug_drug_interaction":12,"renal_dose_conflict":11,
             "duplicate_therapy":9,"dropped_home_med":11,"history_mismatch":9,"drug_condition_conflict":5,
             "adverse_drug_event":11}
    bag=[t for t,w in weights.items() for _ in range(w)]; rng.shuffle(bag)
    S_recs=[]; S_labs=[]; i=0
    while len(S_recs)<remaining and i<len(bag)*6:
        got=take(bag[i%len(bag)]) or take("control"); i+=1
        if got: S_recs.append(got[0]); S_labs.append(got[1])

    records=(L_recs+S_recs)[:N_RECORDS]; labels=(L_labs+S_labs)[:N_RECORDS]
    n_long=len(L_recs)

    # ---- write ----
    base=os.path.join(OUT_DIR,"discrepancy-train")
    with open(base+".jsonl","w") as fo:
        for r in records: fo.write(json.dumps(r)+"\n")
    with open(base+".json","w") as fo: json.dump(records,fo,indent=1)
    with open(base+".labels.jsonl","w") as fo:
        for l in labels: fo.write(json.dumps(l)+"\n")

    from collections import Counter
    dc=Counter(); gr=Counter()
    TEMPORAL={"worsening_trend","dropped_result","dropped_referral","med_discontinued_without_reason"}
    n_temporal=0
    for l in labels:
        if l["is_control"] and not l["has_adverse_event"]: dc["control"]+=1
        for d in l["discrepancies"]:
            dc[d["type"]]+=1
            if d["type"] in TEMPORAL: n_temporal+=1
            for k,v in d.get("grounding",{}).items(): gr[f"{k}:{v}"]+=1
        for a in l["adverse_events"]: dc["adverse_drug_event"]+=1
    uniq=len({r["metadata"]["patient_id"] for r in records})
    multi=len([1 for l in labels if l.get("series",{}).get("n_visits",1)>1])
    summary={"name":"discrepancy-train","records":len(records),"unique_patients":uniq,
             "synthetic":True,"source":"synthea-fhir-r4 (California, US-Core IG) + discrepancy injection",
             "longitudinal":{"records_in_a_visit_series":multi,"series_patients":n_series,
                             "temporal_discrepancies":n_temporal,
                             "point_in_time_records":len(records)-multi},
             "label_distribution":dict(dc),"grounding_provenance":dict(gr),
             "index":[{"id":r["id"],"date":r["metadata"]["date"][:10],"visit_title":r["metadata"]["visit_title"],
                       "visit_index":labels[i].get("series",{}).get("visit_index"),
                       "n_visits":labels[i].get("series",{}).get("n_visits",1),
                       "has_discrepancy":labels[i]["has_discrepancy"],"has_adverse_event":labels[i]["has_adverse_event"],
                       "primary_type":(labels[i]["discrepancies"][0]["type"] if labels[i]["discrepancies"]
                                       else ("adverse_drug_event" if labels[i]["has_adverse_event"] else "control"))}
                      for i,r in enumerate(records)]}
    with open(os.path.join(OUT_DIR,"summary.json"),"w") as fo: json.dump(summary,fo,indent=1)
    print(f"Wrote {len(records)} records ({uniq} unique patients; {multi} in {n_series} visit-series).")
    print("Label distribution:",dict(dc))
    print("Temporal (cross-visit) discrepancies:",n_temporal)
    print("Grounding provenance:",dict(gr))

if __name__=="__main__":
    main()
